//auth
export const OBTENER_USUARIO_ADMIN = "OBTENER_USUARIO_ADMIN";
export const LOGIN_EXITOSO_ADMIN = "LOGIN_EXITOSO_ADMIN";
export const LOGIN_ERROR_ADMIN = "LOGIN_ERROR_ADMIN";
export const CERRAR_SESION_ADMIN = "CERRAR_SESION_ADMIN";
export const INICIO_LOGIN_ADMIN = "INICIO_LOGIN_ADMIN";
export const OBTENER_USUARIO_ERROR_ADMIN = "OBTENER_USUARIO_ERROR_ADMIN";
export const ERROR_EMAIL_ADMIN = "ERROR_EMAIL_ADMIN";
export const ERROR_PASSWORD_ADMIN = "ERROR_PASSWORD_ADMIN";
export const SHOW_ALERT_ADMIN = "SHOW_ALERT_ADMIN";
export const HIDDEN_ALERT_ADMIN = "HIDDEN_ALERT_ADMIN";
export const RESET_EMAIL_ADMIN = " RESET_EMAIL_ADMIN";
export const RESET_PASSWORD_ADMIN = "RESET_PASSWORD_ADMIN";