//auth
export const OBTENER_USUARIO_EMP = "OBTENER_USUARIO_EMP";
export const LOGIN_EXITOSO_EMP = "LOGIN_EXITOSO_EMP";
export const LOGIN_ERROR_EMP = "LOGIN_ERROR_EMP";
export const CERRAR_SESION_EMP = "CERRAR_SESION_EMP";
export const INICIO_LOGIN_EMP = "INICIO_LOGIN_EMP";
export const OBTENER_USUARIO_ERROR_EMP = "OBTENER_USUARIO_ERROR_EMP";
export const ERROR_EMAIL_EMP = "ERROR_EMAIL_EMP";
export const ERROR_PASSWORD_EMP = "ERROR_PASSWORD_EMP";
export const SHOW_ALERT_EMP = "SHOW_ALERT_EMP";
export const HIDDEN_ALERT_EMP = "HIDDEN_ALERT_EMP";
export const RESET_EMAIL_EMP = " RESET_EMAIL_EMP";
export const RESET_PASSWORD_EMP = "RESET_PASSWORD_EMP";
